[project]
name = "django-simple-deploy-hello-world-flyio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django-simple-deploy>=1.0.0",
]
